name: Check tags
on: [push]
jobs:
  e2e:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    name: e2e Test
    steps:
      # This step is for debugging purposes, please don't delete it
      - name: Dump github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
      - name: What is my branch
        run: git checkout ${{ steps.previoustag.outputs.tag }}; ls;
      - name: What is my branch
        run: ls
