name: Check tags

on:
  schedule:
    - cron:  '1 * * * *'
    
jobs:
  e2e:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    name: e2e Test
    steps:
      # This step is for debugging purposes, please don't delete it
      - name: Dump github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Get Latest tag
        id: latesttag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ steps.previoustag.outputs.tag }}
      - name: What is my tag
        run: git branch --show-current 
