name: Check tags
on: [push]
jobs:
  e2e:
    runs-on: ubuntu-20.04
    timeout-minutes: 10
    name: e2e Test
    steps:
      # This step is for debugging purposes, please don't delete it
      - name: Dump github context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.sha }}
      - name: What is my tag
        run: git checkout `git describe --abbrev=0 --tags`
      - name: What is my tag
        run: git branch --show-current 
